@startuml

title heart rate check Sequence

participant "Event Repository" as ER
participant "Monitoring Device" as MD
participant "Monitoring Service" as MS
participant "Alert Service" as AS
participant "Patient Repository" as PR
actor Nurse as N

' Interaction flow
MD ->  MS: Device sends heart-rate measurement
MS -> MS: System associates it with the patient
MS -> PR: System retrieves/checks thresholds
MS -> MS: System evaluates the measurement
MS -> MS: Abnormality is detected
MS -> ER: Event is stored
MS -> AS: create/send alert
AS -> N: notify nurse
alt Alert acknowledged within 60 seconds
N -> AS: acknowledge alert
AS -> ER: update alert status
else Alert not acknowledged within 60 seconds
    AS-> AS: escalate alert
end

@enduml